kind: ConfigMap
apiVersion: v1
metadata:
 name: as3-template
 namespace: zhen
 labels:
   f5type: virtual-server
   as3: "true"
data:
 template: |
   {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "id":"1847a369-5a25-4d1b-8cad-5740988d4423",
        "schemaVersion": "3.16.0",
        "Zhen": {
                "class": "Tenant",
                "Zhen_vs": {
                    "class": "Application",
                    "template": "http",
                    "serviceMain": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.1.10.102"
                        ],
                        "virtualPort": 80,
                        "redirect80": false,
                        "persistenceMethods": [],
                        "pool": "Zhen_pool"
                    },
                    "Zhen_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "shareNodes": true,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        } 
    }
