apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhen
  namespace: zhen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zhen
  template:
    metadata:
      labels:
        app: zhen
    spec:
      containers:
      - name: coffee
        image: orwelion/nginx-hello:zhen
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zhen-svc
  namespace: zhen
  labels:
    cis.f5.com/as3-tenant: Zhen
    cis.f5.com/as3-app: Zhen_vs
    cis.f5.com/as3-pool: Zhen_pool
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: zhen
