apiVersion: v1
kind: Service
metadata:
 name: hackazon
 namespace: hackazon
 labels:
   app: hackazon
spec:
 ports:
 - name: hackazon
   port: 8081
   protocol: TCP
   targetPort: 80
 type: NodePort
 selector:
   app: hackazon
